# Site settings
title: Linux, Simplified
description: A collection of tips, documentation, and snippets for people migrating from Mac or Windows to Linux on the desktop
baseurl: "/linux-simplified/"
url: "https://bnvk.github.io/"
twitter_username: brennannovak
github_username:  bnvk

# Build settings
markdown: kramdown
